// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// vol2birdVersion
Rcpp::CharacterVector vol2birdVersion();
RcppExport SEXP _Rvol2bird_vol2birdVersion() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(vol2birdVersion());
    return rcpp_result_gen;
END_RCPP
}
// runVol2bird
Rcpp::NumericVector runVol2bird(const Rcpp::CharacterVector& inn, const Rcpp::CharacterVector& out, const Rcpp::List& options);
RcppExport SEXP _Rvol2bird_runVol2bird(SEXP innSEXP, SEXP outSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type inn(innSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type out(outSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(runVol2bird(inn, out, options));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Rvol2bird_vol2birdVersion", (DL_FUNC) &_Rvol2bird_vol2birdVersion, 0},
    {"_Rvol2bird_runVol2bird", (DL_FUNC) &_Rvol2bird_runVol2bird, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rvol2bird(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
