// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// volv
Rcpp::CharacterVector volv();
RcppExport SEXP _vol2birdR2_volv() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(volv());
    return rcpp_result_gen;
END_RCPP
}
// volv2
Rcpp::CharacterVector volv2(const Rcpp::CharacterVector& inn, const Rcpp::CharacterVector& out);
RcppExport SEXP _vol2birdR2_volv2(SEXP innSEXP, SEXP outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type inn(innSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type out(outSEXP);
    rcpp_result_gen = Rcpp::wrap(volv2(inn, out));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vol2birdR2_volv", (DL_FUNC) &_vol2birdR2_volv, 0},
    {"_vol2birdR2_volv2", (DL_FUNC) &_vol2birdR2_volv2, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_vol2birdR2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
