# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns vol2bird version
#'
#' @return A character with the vol to bird version
#' 
#' @export
#' 
vol2birdVersion <- function() {
    .Call('_Rvol2bird_vol2birdVersion', PACKAGE = 'Rvol2bird')
}

#' convert pvol file
#'
#' @param inn the input polar volume file as a string
#' @param the output h5 file for the vp
#' @param vol2BirdConfig a list with config options
#' 
#' @return A character with the vol to bird version
#' 
#' @export
#' 
#' @examples
#' runVol2bird(system.file("extdata", "volume.h5", package = "bioRad"), t<-tempfile(), vol2BirdConfig )
#' vp<-bioRad::read_vpfiles(t)
#' plot(vp)
#' 
runVol2bird <- function(inn, out, options) {
    .Call('_Rvol2bird_runVol2bird', PACKAGE = 'Rvol2bird', inn, out, options)
}

