# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns vol2bird version
#'
#' @return A character with the vol to bird version
#' 
#' 
vol2birdVersion <- function() {
    .Call(`_Rvol2bird_vol2birdVersion`)
}

#' convert pvol file
#'
#' @param inn the input polar volume file as a string
#' @param the output h5 file for the vp
#' 
#' @return A character with the vol to bird version
#' 
#' 
#' @examples
#' runVol2bird(system.file("extdata", "volume.h5", package = "bioRad"), t<-tempfile() )
#' vp<-bioRad::read_vpfiles(t)
#' plot(vp)
#' 
runVol2bird <- function(inn, out) {
    .Call(`_Rvol2bird_runVol2bird`, inn, out)
}

