# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

volv <- function() {
    .Call(`_vol2birdR2_volv`)
}

volv2 <- function(inn, out) {
    .Call(`_vol2birdR2_volv2`, inn, out)
}

